
name: Publish Release

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:         
      contents: write     
    steps:
      - uses: actions/checkout@v5
      - name: Setup env
        run: |
          echo "CUR_TAG=${{ github.ref_name }}" >> $GITHUB_ENV
          echo "BASE_TAG=$(cat ./VERSION)" >> $GITHUB_ENV
          
          # --- FOR TESTING ONLY ---
          # i forcefully set the branch to my feature branch so it finds the artifacts
          echo "BRANCH=test-release-feature" >> $GITHUB_ENV
          
          # Mock these values so the workflow doesn't crash looking for a real release
          echo "BUILD_NO=${{ github.run_number }}" >> $GITHUB_ENV
          echo "PRE_TAG=v0.0.0" >> $GITHUB_ENV
          echo "PRERELEASE=true" >> $GITHUB_ENV
          
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v5.0.0
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
      - name: Prepare Assets
        run: |
          BUCKET_NAME="aloui-ikram-harbor-artifacts-2025"
          aws s3 ls s3://${BUCKET_NAME}/${{ env.BRANCH }}/ > s3_files.txt
          src_offline_package=$(grep "harbor-offline-installer" s3_files.txt | grep ".tgz$" | tail -n 1 | awk '{print $4}')
          src_online_package=$(grep "harbor-online-installer" s3_files.txt | grep ".tgz$" | tail -n 1 | awk '{print $4}')
          src_offline_bundle="${src_offline_package}.bundle"
          src_online_bundle="${src_online_package}.bundle"
          
          dst_offline_package="harbor-offline-installer-${{ env.CUR_TAG }}.tgz"
          dst_online_package="harbor-online-installer-${{ env.CUR_TAG }}.tgz"
          dst_offline_bundle="${dst_offline_package}.bundle"
          dst_online_bundle="${dst_online_package}.bundle"
          
          assets_path=$(pwd)/assets
          mkdir -p $assets_path
          
          source tools/release/release_utils.sh
          aws s3 cp s3://${BUCKET_NAME}/${{ env.BRANCH }}/${src_offline_package} $assets_path/$dst_offline_package
          aws s3 cp s3://${BUCKET_NAME}/${{ env.BRANCH }}/${src_online_package} $assets_path/$dst_online_package
          aws s3 cp s3://${BUCKET_NAME}/${{ env.BRANCH }}/${src_offline_bundle} $assets_path/$dst_offline_bundle
          aws s3 cp s3://${BUCKET_NAME}/${{ env.BRANCH }}/${src_online_bundle} $assets_path/$dst_online_bundle

          # Generate checksums
          cd $assets_path
          md5sum $dst_offline_package > md5sum
          md5sum $dst_online_package >> md5sum
          cd ..
        
          echo "OFFLINE_PACKAGE_PATH=$assets_path/$dst_offline_package" >> $GITHUB_ENV
          echo "ONLINE_PACKAGE_PATH=$assets_path/$dst_online_package" >> $GITHUB_ENV
          echo "OFFLINE_BUNDLE_PATH=$assets_path/$dst_offline_bundle" >> $GITHUB_ENV
          echo "ONLINE_BUNDLE_PATH=$assets_path/$dst_online_bundle" >> $GITHUB_ENV
          echo "MD5SUM_PATH=$assets_path/md5sum" >> $GITHUB_ENV
          
      - name: Setup Docker
        uses: docker-practice/actions-setup-docker@master
        with:
          docker_version: 20.10
          docker_channel: stable
      - name: Publish Images
        run: |
          tar -zxf ${{ env.OFFLINE_PACKAGE_PATH }}
          docker load -i ./harbor/harbor.${{ env.BASE_TAG }}.tar.gz
          images="$(docker images --format "{{.Repository}}" --filter=reference='goharbor/*:${{ env.BASE_TAG }}' | xargs)"
          source tools/release/release_utils.sh
          publishImages ${{ env.CUR_TAG }} ${{ env.BASE_TAG }} "${{ secrets.DOCKER_HUB_USERNAME }}" "${{ secrets.DOCKER_HUB_PASSWORD }}" $images
          publishPackages ${{ env.CUR_TAG }} ${{ env.BASE_TAG }} ${{ github.actor }} ${{ secrets.GITHUB_TOKEN }} $images
      - name: Generate release notes
        run: |
          release_notes_path=$(pwd)/release-notes.txt
          source tools/release/release_utils.sh && generateReleaseNotes "${{ env.CUR_TAG }}" "${{ env.PRE_TAG }}" "${{ secrets.GITHUB_TOKEN }}" "${{ github.repository }}" "$release_notes_path"
          echo "RELEASE_NOTES_PATH=$release_notes_path" >> $GITHUB_ENV
      - name: RC Release
        uses: softprops/action-gh-release@v2
        if: ${{ env.PRERELEASE == 'true' }}
        with:
          body_path: ${{ env.RELEASE_NOTES_PATH }}
          files: |
            ${{ env.OFFLINE_PACKAGE_PATH }}
            ${{ env.OFFLINE_BUNDLE_PATH }}
            ${{ env.MD5SUM_PATH }}
      - name: GA Release
        uses: softprops/action-gh-release@v2
        if: ${{ env.PRERELEASE == 'false' }}
        with:
          body_path: ${{ env.RELEASE_NOTES_PATH }}
          files: |
            ${{ env.OFFLINE_PACKAGE_PATH }}
            ${{ env.OFFLINE_BUNDLE_PATH }}
            ${{ env.ONLINE_PACKAGE_PATH }}
            ${{ env.ONLINE_BUNDLE_PATH }}
            ${{ env.MD5SUM_PATH }}